### ISSUE TITLE
‘ZE_COMMAND_QUEUE_FLAG_IN_ORDER’ was not declared in this scope

### ISSUE THREAD

**Issue by kev-liuht** [intel/compute-benchmarks#16]
Hello, I am facing an issue during "cmake --build . --config Release" on Ubuntu 22.04. Am I missing dependencies or is it referencing a missing parameter?

![image](https://github.com/intel/compute-benchmarks/assets/102651507/34c562af-83ae-4a6a-a60c-373a5caa931c)

**Comment by MichalMrozek** [comment]
It means you have old version of L0 loader in the system.
Please fetch / build & install latest from here:
https://github.com/oneapi-src/level-zero-spec
If you do not want to build, please install latest release:
https://github.com/oneapi-src/level-zero-spec/releases/tag/v1.8

**Comment by kev-liuht** [comment]
I see, thanks for your help!
